from river.datasets import synth
from utils import concept_drift
import itertools


META_STREAM_SIZE = 2000

DRIFT_POSITIONS = [500, 1000, 1500]

DRIFT_SPEED = [1, 150, 250, 350]

# TRAIN GENERATORS: AGRAWAL, Mixed, LED, Hyperplane, RandomRBF

# TEST GENERATORS: RandomTree, SEA, Sine, STAGGER, Waveform

# IN REAL-WORLD DATA STREAMS EVALUATE USING A CLASSIFIER THAT RELIES ON A CONCEPT DRIFT DETECTOR
# REAL-WORLD DATASTREAMS: Elec2, CreditCard, Phishing, SMSSPAM, Insects, Spam Assassin, Chess


# TO TEST WE CAN USE 2000 STREAMS WITH ONE DRIFT AND ALSO USE A BIG STREAM WITH MULTIPLE DRIFTS.
